### ISSUE TITLE
Plugin loading but doesn't work. Is this set-up correctly?

### ISSUE THREAD

**Issue by santiyounger** [Garulf/Flow-Raindrop#2]
Hey, thanks a lot for this project. I've been really looking forward for this, so thanks a lot, can't wait to use it!

After installing the app and entering `Test Token` in the plugin's setting I typed `rd` in flow launcher and it remains loading but it doesn't work
![image](https://user-images.githubusercontent.com/51902730/180099443-4c47afed-efb4-45d9-99f0-130f29f65f95.png)

## What I did to enter API Token

As shown here: https://developer.raindrop.io/v1/authentication/token
I went to Raindrop > Integrations > For Developers > Create a New App > "Flow Launcher" Copy `Test Token` and I pasted that in `API Token` in Flow Luncher's Plugin's settings

 I've used other plugins in other apps that do it that way with Raindrop. If there's another method involving `Client Secret` or `Client ID` let me know

Thanks a lot

**Comment by az-pz** [comment]
I managed to run it. 
1. When creating the app in raindrop, use https://oauthdebugger.com/debug as site and redirect uri. 
![image](https://user-images.githubusercontent.com/5427064/213816137-4e9d7aeb-99fe-4180-8149-7cda7d820b08.png)
2. From your browser, go to https://api.raindrop.io/v1/oauth/authorize?client_id=<client_id>&redirect_uri=https:%2F%2Foauthdebugger.com%2Fdebug .
Replace the client_id in the url. 
3. Click on allow on the webpage. It will redirect you to oauthdebugger website. Copy the auth code from the website.
4. Send a curl request with the auth code, client id and client secret:
curl --request POST \
  --url https://raindrop.io/oauth/access_token \
  --header 'Content-Type: application/json' \
  --data '{
  "code": "<copied auth code>",
  "client_id": "<client id>",
  "redirect_uri": "https://oauthdebugger.com/debug",
  "client_secret": "<client secret here>",
  "grant_type": "authorization_code"
}'

5. You will get access_token in the reponse. Paste that token in flow launcher plugin setting.

Reference: https://developer.raindrop.io/v1/authentication/token

**Comment by githubxnoob** [comment]
anyone able to get this working? its not working when following above method. curl request never gives access token.

this is what i get as a response  `Redirecting to https://api.raindrop.io/v1/oauth/access_token`

**Comment by rlodbrok** [comment]
Nope, i do get the RD token but when using it get...
main.py", line 65 while ... , page=page)): 
SyntaxError: invalid syntax

**Comment by Garulf** [comment]
Should be able to goto: https://app.raindrop.io/settings/integrations

![image](https://github.com/Garulf/Flow-Raindrop/assets/535299/670914b3-d353-4b5a-af32-a16fddf1b554)

![image](https://github.com/Garulf/Flow-Raindrop/assets/535299/a81befcc-b93e-44ed-afb5-78bf0d723337)

![image](https://github.com/Garulf/Flow-Raindrop/assets/535299/40ec157c-bd9f-49f5-89e9-f12e0db2f5ec)

Copy the test  token once created!
