### ISSUE TITLE
PowerToys Run plugin

### ISSUE THREAD

**Issue by realgooseman** [Garulf/Flow-Raindrop#5]
Hi @Garulf,

Great plugin, thanks for the work.
It was my main plugin for a long time with WebSearch but I recently switched to Powertoys Run as it got better and makes one less program to run.

Is it possible to port this Flow Launcher plugin to Powertoys Run ?

I found these pages documenting Powertoys Run plugins : **[here](https://conductofcode.io/post/creating-custom-powertoys-run-plugins/)** and **[here](https://github.com/hlaueriksson/awesome-powertoys-run-plugins/blob/main/checklist.md)**

Is it too much of a hassle or is it pretty straightforward ?

**Comment by Garulf** [comment]
Hi @realgooseman,

Sorry for the late reply and thank you for taking an interest in my plugin. 

Sadly *Run* only seems to accept C Sharp based plugins and I don't have any interest in supporting plugins in that language long term. Sorry.
